# apiVersion: v1
# kind: ConfigMap
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-wave: "20"
#   name: cluster-monitoring-config
#   namespace: openshift-monitoring
# data:
#   config.yaml: |
#     enableUserWorkload: true
