{{- if .Values.istio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  name: htpasswd
  namespace: istio-system
type: Opaque
data:
  auth: aW50ZXJuYWw6e1NIQX1pZVNWNTVRYytlUU9hWURSU2hhL0Fqek5USkU9Cg==
  rawPassword: ZGVtbw==
{{ end }}
