# Default values for discounts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

discounts-blue:
  replicaCount: 2
  nameOverride: discounts-umbrella
  fullnameOverride: "discounts-blue"
  log:
    level: DEBUG
  version: blue
  image:
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  podAnnotations:
    prometheus.io/scrape: "true"
discounts-green:
  nameOverride: discounts-umbrella
  fullnameOverride: "discounts-green"
  log:
    level: DEBUG 
  version: green
  image:
    tag: "latest"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"    
discountsNetworkingOnline:
  nameOverride: discounts-umbrella
  fullnameOverride: "discounts-umbrella-online"
  router:
    enabled: false
discountsNetworkingOffline:
  nameOverride: discounts-umbrella
  fullnameOverride: "discounts-umbrella-offline"
  router:
    enabled: false
    
products-blue:
  replicaCount: 2
  nameOverride: products-umbrella
  fullnameOverride: "products-blue"
  log:
    level: DEBUG
  discountsApi:
    url: http://discounts-umbrella-online:8080
  version: blue
  image:
    tag: "latest"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
products-green:
  nameOverride: products-umbrella
  fullnameOverride: "products-green"
  log:
    level: DEBUG
  discountsApi:
    url: http://discounts-umbrella-online:8080
  version: green
  image:
    tag: "latest"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https" 
productsNetworkingOnline:
  nameOverride: products-umbrella
  fullnameOverride: products-umbrella-online

productsNetworkingOffline:
  nameOverride: products-umbrella
  fullnameOverride: "products-umbrella-offline"

global:
  istio:
    enabled: false

nameOverride: "shop-umbrella" 

fullnameOverride: ""






