apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-blue-green
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: blue-green-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: pipelines
    repoURL: https://github.com/davidseve/cloud-native-blue-green.git
    targetRevision: istio
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false