apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-blue-green
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    name: ''
    namespace: blue-green-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/quarkus-helm-umbrella/chart-blue-green
    repoURL:  https://github.com/davidseve/cloud-native-blue-green.git
    targetRevision: istio
    helm:
      valueFiles:
        - values/values-istio.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false